--데이터 입력시 제약을 걸어서 무조건 입력받게 하기
CREATE TABLE TABLE_NOTNULL (
LOGIN_ID VARCHAR2(20)NOT NULL,
LOGIN_PWD VARCHAR2(20)NOT NULL,
TEL VARCHAR2(20)
);

DESC TABLE_NOTNULL;

INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD,TEL)
VALUES ('TEST','1111','000-0000-0000');

INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD)
VALUES ('TEST2','2222');

UPDATE TABLE_NOTNULL
SET TEL = '010-9999-9999';

SELECT * FROM TABLE_NOTNULL;

SELECT * FROM USER_CONSTRAINTS;

ALTER TABLE TABLE_NOTNULL
MODIFY (TEL NOT NULL);

CREATE TABLE TABLE_UNIQUE (
LOGIN_ID VARCHAR2(20) UNIQUE,
LOGIN_PWD VARCHAR2(20) NOT NULL,
TEL VARCHAR2(20)
);

DESC TABLE_UNIQUE;

INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PWD,TEL)
VALUES('AAA','1234','111-111-1111');

INSERT INTO TABLE_UNIQUE(LOGIN_ID,LOGIN_PWD,TEL)
VALUES(NULL,'1234','111-111');

SELECT * FROM TABLE_UNIQUE;

--PRIMARY KEY를 제약 조건으로 걸면 UNIQUE, NOT NULL, INDEX도 설정된다.
CREATE TABLE TABLE_PK (
LOGIN_ID VARCHAR2(20) PRIMARY KEY,
LOGIN_PWD VARCHAR2(20) NOT NULL,
TEL VARCHAR2(20) 
);

DESC TABLE_PK;

INSERT INTO TABLE_PK(LOGIN_ID,LOGIN_PWD,TEL)
VALUES('JJIEUN','1234','111-111-1111');

--FOREIGN KEY 정규화
SELECT * FROM EMP;

INSERT INTO EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES(9999,'HONG','CLERK','7788',TO_DATE('2023-02-28', 'YYYY/MM/DD'),1200,NULL, 50);

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP','DEPT');

SELECT * FROM DEPT;

CREATE TABLE DEPT_FK (
DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(20),
LOC VARCHAR2(20)
);

DESC DEPT_FK;

CREATE TABLE EMP_FK (
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB VARCHAR2(10),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);

INSERT INTO DEPT_FK VALUES (10,'AAA','DANGSAN');

INSERT INTO DEPT_FK VALUES (20,'BBB','ILSAN');

INSERT INTO EMP_FK VALUES (2222,'TEXT_USER','TEST_JOB',NULL,TO_DATE('2023-02-28','YYYY-MM-DD'),
3000,NULL,20);

DESC EMP_FK;

SELECT * FROM DEPT_FK;

SELECT * FROM EMP_FK;

/*
CREATE TABLE TABLE_CHECK (
LOGIN_ID VARCHAR2(20) CONSTRAINT TABLE_CHECK_LOGIN_PK PRIMARY KEY,
LOGIN_PWD VARCHAR2(20) CONSTRAINT TABLE_LOGINPWD_CH CHECK(LENGTH(LOGIN_PWD) > 3),
TEL VARCHAR2(20)
);

DESC TABLE_CHECK;

INSERT INTO TABLE_CHECK VALUES ('TESE_ID','1234','1111-2222');
*/

CREATE TABLE TABLE_DEFAULT (
LOGIN_ID VARCHAR2(20) CONSTRAINT TABLE_CHECK_LOGIN_PK02 PRIMARY KEY,
LOGIN_PWD VARCHAR2(20) CONSTRAINT TABLE_LOGINPWD_CH02 CHECK(LENGTH(LOGIN_PWD) > 3),
TEL VARCHAR2(20),
REGDATE DATE DEFAULT SYSDATE 
);
INSERT INTO TABLE_DEFAULT (LOGIN_ID, LOGIN_PWD, TEL) VALUES ('TESE_ID02','1234','1111-2222-3333');
SELECT * FROM TABLE_DEFAULT;

--연습 문제
CREATE TABLE DEPT_CONST (
DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DEPTNO_UNIGUE UNIQUE,
LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);

DESC DEPT_CONST;

CREATE TABLE EMP_CONST02 (
EMPNO NUMBER(4) CONSTRAINT EMPCONST02_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10) CONSTRAINT EMPCONST02_ENAME_UNQ UNIQUE,
JOB VARCHAR2(9),
TEL VARCHAR2(20)CONSTRAINT EMPCONST02_TEL_UNQ UNIQUE,
HIREDATE DATE,
SAL NUMBER(7,2) CONSTRAINT EMPCONST02_TEL_CHK CHECK(SAL BETWEEN 1000 AND 9999),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPCONST02_TEL_FK REFERENCES DEPT_CONST02 (DEPTNO)
);

DESC EMP_CONST02;

SELECT * FROM EMP_CONST02;

CREATE TABLE DEPT_CONST02 (
  DEPTNO NUMBER(2) CONSTRAINT DEPTCONST02_DEPTNO_PK PRIMARY KEY, 
  DNAME VARCHAR2(14)CONSTRAINT DEPTCONST02_DEPTNO_UNIGUE UNIQUE, 
  LOC VARCHAR2(13) CONSTRAINT DEPTCONST02_LOC_NN NOT NULL
);

DESC DEPT_CONST02