SELECT * FROM DICT;

SELECT * FROM DICTIONARY;

SELECT TABLE_NAME FROM USER_TABLES;

SELECT OWNER, TABLE_NAME FROM ALL_TABLES;

SELECT * FROM DBA_TABLES;

--INDEX는 검색을 빨리 해야 할 때
SELECT * FROM USER_INDEXES;

--INDEX 만들기
CREATE INDEX IDX_EMP_SAL
ON EMP (SAL);

DROP INDEX IDX_EMP_SAL;


--VIEW(SYS에서 권한을 줘야 생성 가능)
CREATE VIEW VW_EMP20 AS 
(SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO = 20);

SELECT * FROM USER_VIEWS;

SELECT * FROM  VW_EMP20;

DROP VIEW  VW_EMP20;

SELECT * FROM EMP;

SELECT ROWNUM,E.*
FROM EMP E;

SELECT ROWNUM,E.*
FROM EMP E
ORDER BY SAL DESC;

--FROM절에 쓰인 서브쿼리를 INLINE VIEW라고도 한다. 많이 쓰임
SELECT ROWNUM,E.*
FROM (SELECT * FROM EMP E ORDER BY SAL DESC) E
WHERE ROWNUM <= 5;

--가상 테이블
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
FROM E
WHERE ROWNUM <= 5;

--SEQUENCE AUTO-INCREAMENT
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 90
MINVALUE 0
NOCYCLE
CACHE 2;

SELECT * FROM USER_SEQUENCES;

CREATE TABLE DEPT_SEQUENCE AS SELECT * FROM DEPT WHERE 1 = 0;

SELECT * FROM DEPT_SEQUENCE;

INSERT INTO DEPT_SEQUENCE (DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');

--동의어
CREATE SYNONYM E FOR EMP;

SELECT * FROM E;

--연습 문제
--1번
CREATE TABLE EMPIDX AS SELECT * FROM EMP;

SELECT * FROM USER_INDEXES;

CREATE INDEX IDX_EMPIDX_EMPNO
ON EMPIDX(EMPNO);

CREATE OR REPLACE VIEW EMPIDX_OVER15 AS (
SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM,'O','X') AS COMM
FROM EMPIDX
WHERE SAL > 1500
);

SELECT * FROM EMPIDX_OVER15;

CREATE TABLE DEPTSEQ AS SELECT * FROM DEPT;

CREATE SEQUENCE SEQ_DEPTSEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 99
MINVALUE 1
NOCYCLE
NOCACHE;

INSERT INTO DEPTSEQ(DEPTNO,DNAME,LOC)
VALUES (SEQ_DEPTSEQ.NEXTVAL,'WEB','BUSAN');

SELECT * FROM DEPTSEQ;











