--기존 테이블을 쓰지 않고 새로운 테이블 만들어서 넣기
CREATE TABLE DEPT_TEMP
AS SELECT * FROM DEPT;
SELECT*FROM DEPT_TEMP;

--EMP 테이블 데이터를 그대로 들고와서 TABLE 만들기 EMP_TEMP10
CREATE TABLE EMP_TEMP10
AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP10;

--INSERT
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (60, 'NETWORK', NULL);
SELECT * FROM DEPT_TEMP;

CREATE TABLE EMP_TEMP
AS SELECT * FROM EMP WHERE 1 = 0;
SELECT * FROM EMP_TEMP;

INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'홍길동','PRESIDENT',NULL,'2023/02/27',5000, 1000, 10);
INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (9999,'이몽룡','PRESIDENT',NULL,'2023/02/27',5000, 1000, 10);
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES ((SELECT MAX(EMPNO) - 1 FROM EMP_TEMP),'성춘향','PRESIDENT',NULL,SYSDATE,5000, 1000, 10);
SELECT MAX(EMPNO) - 10 FROM EMP_TEMP;
SELECT * FROM EMP_TEMP;


--UPDATE
CREATE TABLE DEPT_TEMP02 AS SELECT * FROM DEPT;

UPDATE DEPT_TEMP02 SET LOC = 'SEOUL';

UPDATE DEPT_TEMP02 SET DNAME = 'DATABASE', LOC = 'ILSAN'
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP02;

COMMIT; --COMMIT 하면 ROLLBACK 안됨

ROLLBACK; --TRANSACTION

--EMP_TAMP11 급여가 2500 이하인 사람의 COMM 50으로 수정
CREATE TABLE EMP_TEMP11 AS SELECT * FROM EMP;
UPDATE EMP_TEMP11 SET COMM = 50 WHERE SAL <= 2500;
SELECT * FROM EMP_TEMP11;

UPDATE DEPT_TEMP02 SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40),
LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

UPDATE DEPT_TEMP02 SET
(DNAME, LOC) = (SELECT DNAME,LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

DELETE FROM EMP_TEMP10
WHERE JOB = 'SALESMAN';
ROLLBACK;
SELECT * FROM EMP_TEMP10;

-- EMP_TEMP10에서 급여가 3000 이상인 사람 정리해고 하기.
DELETE FROM EMP_TEMP10
WHERE SAL >= 3000;
ROLLBACK;
SELECT * FROM EMP_TEMP10;

-- 연습 문제
-- 1번
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

INSERT INTO CHAP10HW_DEPT (DEPTNO,DNAME,LOC)
VALUES (50,'ORACLE','BUSAN');
INSERT INTO CHAP10HW_DEPT (DEPTNO,DNAME,LOC)
VALUES (60,'SQL','ILSAN');
INSERT INTO CHAP10HW_DEPT (DEPTNO,DNAME,LOC)
VALUES (70,'SELECT','INCHEON');
INSERT INTO CHAP10HW_DEPT (DEPTNO,DNAME,LOC)
VALUES (80,'DML','BUNDANG');

SELECT * FROM CHAP10HW_DEPT;

-- 2번
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7201,'TEST_USER1','MANAGER',7788,'2016-01-02',4500,NULL,50);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7202,'TEST_USER2','CLERK',7201,'2016-02-21',1800,NULL,50);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7203,'TEST_USER3','ANALYST',7201,'2016-04-11',3400,NULL,60);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7204,'TEST_USER4','SALESMAN',7201,'2016-05-11',2700,300,60);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7205,'TEST_USER5','CLERK',7201,'2016-07-20',2600,NULL,70);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7206,'TEST_USER6','CLERK',7201,'2016-09-18',2600,NULL,70);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7207,'TEST_USER7','LECTURER',7201,'2016-10-28',2300,NULL,80);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (7208,'TEST_USER8','STUDENT',7201,'2018-03-09',1200,NULL,80);

SELECT * FROM CHAP10HW_EMP;

ROLLBACK;

-- 3번
SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO = 50;

UPDATE CHAP10HW_EMP SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO = 50);

-- 4번
UPDATE CHAP10HW_EMP SET
SAL = SAL * 1.1,
DEPTNO = 80
WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60); 

SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60;

SELECT * FROM CHAP10HW_EMP;

-- 5번
DELETE FROM CHAP10HW_EMP
WHERE EMPNO IN(SELECT E.EMPNO
FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND GRADE = 5);

/*
SELECT E.EMPNO
FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND GRADE = 5;
*/

SELECT * FROM CHAP10HW_EMP;



