-- JOIN
-- table 두 개 이상을 엮어서 쓰는 것

SELECT * FROM EMP;
SELECT * FROM EMP;

SELECT * FROM EMP, DEPT
ORDER BY EMPNO;

SELECT * FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;

--오라클에서만 쓸 수 있다. INNER JOIN
SELECT E.EMPNO, E.ENAME, E.MGR, E.HIREDATE, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND E.SAL >= 3000
ORDER BY D.DEPTNO, E.EMPNO;
--등가조인

--SALGRADE 비등가 조인
SELECT * FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

--SHLF JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
E2.EMPNO AS MANAGER_EMPNO,
E2.ENAME AS MANAGER_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+);
--조건을 만족하지 않더라도 일단 표시는 해라... NULL이라도 뿌려라

--연습 문제 1~4번
SELECT * FROM DEPT, EMP
WHERE SAL >= 3000
ORDER BY EMPNO;

--AVG_SAL, MAX_SAL, MIN_SAL, CNT
SELECT D.DEPTNO, D.DNAME, TRUNC(AVG(SAL)), MAX(SAL), MIN(SAL)
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO, DNAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, JOB, SAL
FROM DEPT D, EMP E
ORDER BY D.DEPTNO, E.ENAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, S.LOSAL, S.HISAL, S.GRADE
FROM DEPT D, EMP E, SALGRADE S
ORDER BY D.DEPTNO, E.EMPNO, E.MGR, S.LOSAL, S.HISAL,S.GRADE;

























