-- DEPTNO 30
SELECT * FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

SELECT * FROM EMP
WHERE DEPTNO = 20 OR JOB = 'SALESMAN';

-- SAL 3000 이상
SELECT * FROM EMP
WHERE SAL = 3000;
 
--SAL 3000 아닌 사람 뽑아보기...
 SELECT * FROM EMP
 WHERE SAL != 3000;
--!= > <> > ^= 셋 다 쓸 수 있음.

--JOB
 SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'CLERK' OR JOB = 'SALESMAN';
--문자열 ''

--IN 구문으로 바꿔 보기...
SELECT * FROM EMP
WHERE JOB IN('MANAGER','CLERK','SALESMAN');

--IN 구문으로 바꿔 보기...
SELECT * FROM EMP
WHERE JOB NOT IN('MANAGER','CLERK','SALESMAN');

-- 부서 번호가 10, 20인 사람 뽑아보기...
SELECT * FROM EMP
WHERE DEPTNO = 20 OR DEPTNO = 30;

-- 부서 번호가 10, 20인 사람 IN 구문으로 뽑아보기...
SELECT * FROM EMP
WHERE DEPTNO NOT IN('20','30');

-- SAL 2000이상 3000이하 뽑기...
SELECT * FROM EMP
WHERE SAL >= 2000 AND SAL <= 3000;

-- SAL 2000이상 3000이하 BETWEEN으로 뽑기...
SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

-- EMP NO 7000이상 7600이하 뽑기...
SELECT * FROM EMP
WHERE EMPNO >= 7000 AND EMPNO <= 7600;

-- EMP NO 7000이상 7600이하 뽑기...
SELECT * FROM EMP
WHERE EMPNO BETWEEN 7000 AND 7600;

-- 이름이 ABC로 시작하는 사람 뽑기...
SELECT * FROM EMP
WHERE ENAME BETWEEN 'A' AND 'D';

--LIKE
SELECT * FROM EMP
WHERE ENAME LIKE '%S%';
--%, _ 쓸 수 있음.

--LIKE AM
SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';

--M I 있는 사람 뽑아보기
SELECT * FROM EMP
WHERE ENAME LIKE '%M%I%';

--ER 로 끝나는 사람 뽑아보기
SELECT * FROM EMP
WHERE ENAME LIKE '%ER';

--사원 이름이 두 번째 글자가 L 인 사람 뽑기...
SELECT * FROM EMP
WHERE ENAME LIKE '_L%';

--사원 이름이 두 번째 글자가 A 인 사람 뽑기...
SELECT * FROM EMP
WHERE ENAME LIKE '__A%';

--사원 이름이 5글자인 사람 찾기
SELECT * FROM EMP
WHERE ENAME LIKE '_____';

--NULL 체크하기... NULL = 초 체크 안됨.
SELECT * FROM EMP
WHERE COMM IS NOT NULL;

--연습 문제 1번 ~ 6번
SELECT * FROM EMP
WHERE ENAME LIKE '%S';

SELECT EMPNO,ENAME,JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

SELECT * FROM EMP
WHERE (DEPTNO = 20 OR DEPTNO = 30) AND SAL > 2000;
--**DEPTNO IN(20, 30) AND SAL > 2000;

SELECT * FROM EMP
WHERE SAL < 2000 OR SAL > 3000;

SELECT ENAME,EMPNO,SAL,DEPTNO FROM EMP
WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND SAL NOT BETWEEN 1000 AND 2000;

SELECT * FROM EMP
WHERE COMM IS NULL AND MGR IS NOT NULL AND JOB IN ('MANAGER','CLERK')
AND ENAME NOT LIKE '_L%';

















 
 
 

 





