CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;
  
INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

ROLLBACK;

COMMIT;

SELECT * FROM DEPT_TCL;

UPDATE DEPT_TCL SET LOC = 'SEOUL'
WHERE DEPTNO = 30;

COMMIT;

SELECT * FROM DEPT_TCL;

--연습 문제
--1번
CREATE TABLE DEPT_HW AS SELECT * FROM DEPT;

UPDATE DEPT_HW SET DNAME = 'DADABASE', LOC = 'SEOUL'
WHERE DEPTNO = 30;

ROLLBACK;

COMMIT;

SELECT * FROM DEPT_HW;

