server: 
    Port: 9090
spring: 
    output: 
        ansi: 
            enabled: always
    datasource: 
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: KIMJIEUN99
        password: 1112
logging: 
    level: 
        '[com.kimjieun99.replyboard03]': DEBUG
    
mybatis: 
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sqlmapper/**/*.xml

file: 
    path: C:/replyboard03/upload/
  